# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
# Install dependencies and run tests
  build-and-test:
    docker:
      - image: node:16-alpine
    steps:
      - checkout
      - run: npm ci
    #  - run: npm test

  # Build a Docker image and push to Docker Hub
  # Authenticate with Digital Ocean CLI and deploy the app
  deploy:
    docker:
      - image: node:16-alpine
    steps:
      - checkout
      # Allow using Docker commands
      - setup_remote_docker
      - run: bash deploy.sh

workflows:
  version: 2
  # Workflow name
  build-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            # Run after all tests have passed
            - build-and-test
          filters:
            branches:
              # Only deploy on pushes to the master branch
              only: master
