version: 2.1

variables:
- name: IMAGE_TAG
  value: $(git rev-parse --short HEAD)

jobs:
  build:
    docker:
      - image: circleci/node:16

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/ 
          keys: 
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-

      - run:
          name: yarn-install
          command: yarn build

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
          name: Build and push Docker image
          command: | 
            #yarn gencss
            docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$(variables.IMAGE_TAG) .
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push $DOCKER_USERNAME/$IMAGE_NAME:$(variables.IMAGE_TAG)
