import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import Navbar from '../components/Navbar/Navbar'
import styles from '../sass/Home.module.scss'
import Body from '../components/MainBody/Body'
import Footer from '../components/Footer/Footer'



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <Hero />
        <Body/>
        <Footer/>

        
       
      </main>
     

      
    

    </div>
  )
}
